apiVersion: v1
kind: Service
metadata:
  name: nursery-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: nursery-frontend
  ports:
    - protocol: TCP
      port: 80           # External port
      targetPort: 80     # Container port 